### ISSUE TITLE
Feature request: Ability to refresh (=reload) the guide

### ISSUE THREAD

**Issue by theCroh** [hulkrelax/deckfaqs#14]
I'm having a problem where a large guide seems to fail to load completely and is cut off at some point. This happens at least with [this guide](https://gamefaqs.gamespot.com/pc/915112-the-witcher/faqs/64245). At the moment, the only solution seems to be to exit the guide and open it again until it loads successfully. Reload button would simplify this a lot.

**Comment by hulkrelax** [comment]
Thanks for calling this out. I'll take a look when I have some time. Seems like a bug.

**Comment by DJScias** [comment]
Hello there,

Having a smiliar issue with this guide: https://gamefaqs.gamespot.com/ps4/168682-i-am-setsuna/faqs/74778?page=5#Twallusk%20Mountain

Around this part the guide cuts off and goes blank when you scroll further through the menu.

It doesn't seem to fix itself unless you restart it and then load the guide after that part as otherwise it will restart going blank.

Attached is a screenshot showing the "blank" issue after chapter switching.

![20230114235105_1](https://user-images.githubusercontent.com/439655/212522000-bf5d2f7a-53d1-4ef2-9261-bb9f099dbf8a.jpg)

**Comment by hulkrelax** [comment]
v1.6.0 adds a reload feature. Also @DJScias, I have addressed the issue with what you were seeing and it is also fixed in v1.6.0. I will close this issue when it is released on the store officially.

**Comment by DJScias** [comment]
> v1.6.0 adds a reload feature. Also @DJScias, I have addressed the issue with what you were seeing and it is also fixed in v1.6.0. I will close this issue when it is released on the store officially.

Thank you, I'll be sure to check this one as well for testing.

**Comment by DJScias** [comment]
Tested in https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/242#pullrequestreview-1304855226 and this issue no longer happens to me + the refresh button is nice. I hope the main creator of this issue can test the button too eventually.

**Comment by theCroh** [comment]
> Tested in [SteamDeckHomebrew/decky-plugin-database#242 (review)](https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/242#pullrequestreview-1304855226) and this issue no longer happens to me + the refresh button is nice. I hope the main creator of this issue can test the button too eventually.

I'll check it out once it gets released. 👍🏻

**Comment by theCroh** [comment]
I still have the occasional problem where some guides load only partielly but I can confirm that now reloading the guide is much faster and easier. The original request is resolved.
