### ISSUE TITLE
A particular guide crashes Decky, sometimes the system

### ISSUE THREAD

**Issue by Syampuuh** [hulkrelax/deckfaqs#20]
https://gamefaqs.gamespot.com/ps4/718564-metal-gear-solid-v-the-phantom-pain/faqs/72350

For whatever reason, this particular guide crashes the plugin. In-game, this crashes the entire OS and forces a reboot, but otherwise it crashes Decky and displays the following error, before returning to the home screen with Decky disabled.

![image](https://user-images.githubusercontent.com/25516124/216791784-36150404-ff6f-41eb-bd3a-cf8906441f99.png)

Nothing particularly stands out about this guide as different from other HTML guides, except perhaps size? Not sure.

**Comment by adinunzio10** [comment]
I just had this happen with Witcher 3. Was playing it and pulled up a guide. When I chose which guide I wanted I saw it open for a brief moment before my system crashed and had to be force rebooted.

**Comment by hulkrelax** [comment]
The guides may be too large which causes the crashing. I know people have had issues with this in the past but I wasn't able to repro. I'll try with a game open since that seems like maybe related. My guess is that the DOM is too large but I don't know for sure.

**Comment by hulkrelax** [comment]
@Syampuuh I have fixed this in v1.6.0. It is currently in testing on the plugin store, so look out for that. I will close this issue when it is officially release on the store.

**Comment by pencilcheck** [comment]
I use guides like trails of cold steel II and it will crash when I try to open the guide the second time. What it will happen first it will reset then when I try to go in again it will crash the whole steam deck and restart


https://gamefaqs.gamespot.com/ps3/763235-the-legend-of-heroes-trails-of-cold-steel-ii/faqs/73014

**Comment by hulkrelax** [comment]
@pencilcheck I think I identified something else that was causing crashes (irrespective of any particular guide). Check out DeckFAQs v1.7.0 once it is released on the store and see if you get less/no crashes.

**Comment by ForceANature110** [comment]
I'm still getting this on v1.7.0 when using the FF9 guide.

https://gamefaqs.gamespot.com/ps/197338-final-fantasy-ix/faqs/71891/introduction

Often crashes the system and forces a reboot.

Basically makes it unusable for fear of losing progress.

**Comment by pencilcheck** [comment]
1.7.1 seems to stop crashing steam deck and game but the guide still will reset and I have to reopen it again everytime I close and open the side bar.

**Comment by hulkrelax** [comment]
This may be a system level issue. I'm not sure yet. You should see if other plugins reset to their default state after some time. I haven't had time yet to determine what is happening.
